### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by aleksamagicka** [aleksamagicka/waterforce-hwmon#4]
Partial TODO:

- [ ] Relax max RPM deciding based on firmware version retrieval
- [ ] Add writing PWM based on that
- [x] Add sync code for fancontrol
- [ ] Rework pwm_enable to hwmon values
- [x] Write docs
- [x] Make completion waits interruptible
